### ISSUE TITLE
Start failed

### ISSUE THREAD

**Issue by evilz** [tpetricek/elmish-spreadsheet#1]
Hi, 

Nice job, but what are the commands to restore and start dev ?

I got this error :
```
  [25] ./src/spreadsheet.fsproj 352 bytes {0} [built] [failed] [1 error]
    + 11 hidden modules


Make sure Fable server is running on port 61225                                                fable-loader\index.js:107:18)
    at Loader.fableUtils.client.send.then.catch.err (D:\GITHUB\elmish-spreadsheet\node_modules\fable-loader\index.js:107:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) @ multi (webpack)-dev-server/client?http://localhost:8087 ./src/spreadsheet.fsproj
webpack: Failed to compile.
```

Thank

**Comment by tpetricek** [comment]
The following should work, assuming you are in the root folder:

```
yarn install              # Install JavaScript packages, you can use npm install too
dotnet restore            # Install .NET dependencies, most notably Fable
code .                    # If you're using VS Code, open it here 
cd src                    # Go to the source directory
dotnet fable yarn-start   # Run fable in the background, you can use npm-start too
```

**Comment by evilz** [comment]
Yes, I did not run the `dotnet fable` ... now the error message is so clear to me.
Thank again, I learn some other syntax with this workshop ! 
You are awesome
👍
